# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dc_power', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SolarData',
                'verbose_name_plural': 'SolarData',
            },
        ),
        migrations.CreateModel(
            name='SolarMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('installation_key', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('system_capacity', models.IntegerField(blank=True, help_text='In Kw', null=True)),
                ('azimuth', models.IntegerField(blank=True, null=True)),
                ('array_type', models.IntegerField(blank=True, null=True)),
                ('module_type', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('tilt', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dataset', models.CharField(blank=True, max_length=5, null=True)),
                ('timeframe', models.CharField(blank=True, choices=[('HOURLY', 'HOURLY'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'SolarUser',
                'verbose_name_plural': 'SolarUser',
            },
        ),
        migrations.AddField(
            model_name='solardata',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oorjan_app.SolarMetaData'),
        ),
    ]
