# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorjan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarReferenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dc_power', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SolarReferenceData',
                'verbose_name_plural': 'SolarReferenceData',
            },
        ),
        migrations.AlterModelOptions(
            name='solarmetadata',
            options={'verbose_name': 'SolarMetaData', 'verbose_name_plural': 'SolarMetaData'},
        ),
    ]
